name: 'Test'
description: 'Test'
author: 'Laurits7'
runs:
  using: 'docker'
  image: 'clelange/cc7-cmssw-cvmfs:latest'
  args:
    - "--cap-add SYS_ADMIN --cap-add=MKNOD --security-opt apparmor=unconfined -e CVMFS_MOUNTS="cms.cern.ch" -device /dev/fuse /bin/bash"
